services:
  - type: web
    name: tg-volume-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: PORT
        value: 8443